<?php
  /* модуль архивации rar */
if (!defined('RAPIDGET')) {
    die ("not load primary script");
}

$OS=strtoupper(substr(PHP_OS, 0, 3));
    if(count($_GET["files"]) < 1)
        {
            echo "<div id='x1' style='padding:10px; border: 1px dashed red;'> Выберите хотябы один файл</div>";
        }
        elseif(!file_exists("rar") & !file_exists("rar.exe") & !file_exists("/usr/bin/rar") & !file_exists("/bin/rar"))
        {
            switch($OS)
            {
                case "WIN": $OS="Microsoft Windows"; break;
                case "LIN": $OS="Linux"; break;
                case "FRE": $OS="FreeBSD"; break;
            }
            echo "<div id='x1' style='padding:10px; border: 1px dashed red;'> Вам следует установить rar архиватор, т.к. он не был найден в системе. Для этого пройдите по <a href='http://rarlabs.com/download.htm'>ссылке</a>, скачайте архиватор для системы $OS и поместите файл rar".(($OS=="Microsoft Windows") ? ".exe" : "")." из архива в папку со скриптом</div>";
        }
        else
        {
            if(!$is_windows)
            {
                if(!file_exists("/usr/bin/rar") & !file_exists("/bin/rar"))
                    $cmd="./rar";
                else
                    $cmd="rar";
                if(`$cmd`=="")
                {
                 echo "<div id='x1' style='padding:10px; border: 1px dashed red;'> Ошибка запуска программы-архиватора.<br>Причина: ";
                 echo `$cmd 2>&1`;
                 echo "</div>";
                }
            }
?>
<form method="post">
<input type=hidden name=act value="rar_go">
<table align="center">
<tr><td align='center'>
<?php
        
        for($i = 0; $i < count($_GET["files"]); $i++){
           $file = $list[$_GET["files"][$i]];
           //echo $i;
           if(strpos($file["name"], $workpath)===0 && strpos($file["name"], "/../")===false && !in_array(basename($file["name"]),$systemfile)){
?>
        <input type=hidden name="files[]" value="<?php echo $_GET["files"][$i]; ?>">
<?php
           echo "<b>".basename($file["name"])."</b>; ";
            }
        }
?>
</td></tr>
<tr><td>
<table border='1' align='center'>
<tr><td align='center'>степень сжатия</td><td align='center'>имя архива</td><td align='center'>размер части (мб)</td><td align='center'>пароль</td><td align='center'>recovery (%)</td><td align='center'>блокировать</td></tr>
<tr>
<td align='center'>
<select name='compression_level'>
<option value='0'>0 - без сжатия   -[30%CPU]</option>
<?php if($scriptest=='ok'){
echo "<option value='1'>1 - скоростное   -[45%CPU]</option><option value='2'>2 - быстрое      -[55%CPU]</option><option value='3'>3 - обычное      -[70%CPU]</option><option value='4'>4 - хорошое      -[90%CPU]</option><option value='5'>5 - максимальное -[100%CPU]</option>";
}
?>
</select>
</td>
<td align='center'><input type='text' name='archname' size='15' value='<?php echo basename($file["name"]).".rar"?>' id='archname'></td>
<td align='center'><input type='text' name='part_size' size='10'></td>
<td align='center'><input type='text' name='password' size='10'></td>
<td align='center'><input type='text' name='recovery' size='5'></td>
<td align='center'><input type='checkbox' name='block'></td>
</tr>
<tr><td colspan='6' align='center'>комментарий к архиву:</td></tr>
<tr><td colspan='6' align='center'><textarea name='comment'></textarea></td></tr>
<tr><td colspan='6'><input type='checkbox' name='delifsuccess'> удалить заархивированные файлы при успешном завершении</td></tr>
</table>
</td></tr>
<tr>
<td align='center'><input type=submit value="Архивировать"></td></tr>
</table></form>
<?php  }
/*
This file was generated by php_mega_coder utility ©. Artificial intelligence was here.
*/
?>